from project.beverage.beverage import Beverage
from project.beverage.coffee import Coffee
from project.beverage.tea import Tea
from project.food.dessert import Dessert
from project.food.soup import Soup
from project.product import Product

product = Product("coffee", 2.5)
print(product.__class__.__name__)
print(product.name)
print(product.price)
beverage = Beverage("coffee", 2.5, 50)
print(beverage.__class__.__name__)
print(beverage.__class__.__bases__[0].__name__)
print(beverage.name)
print(beverage.price)
print(beverage.milliliters)
soup = Soup("fish soup", 9.90, 230)
print(soup.__class__.__name__)
print(soup.__class__.__bases__[0].__name__)
print(soup.name)
print(soup.price)
print(soup.grams)
soup = Soup("fish soup", 9.90, 230)
print(soup.__class__.__name__)
print(soup.__class__.__bases__[0].__name__)
print(soup.name)
print(soup.price)
print(soup.grams)
dessert = Dessert("Ice Cream", 5, 110, 1500)
print(dessert.__class__.__name__)
print(dessert.__class__.__bases__[0].__name__)
print(dessert.name)
print(dessert.price)
print(dessert.grams)
coffee = Coffee("Swarz", 5, 110, 10)
print(coffee.__class__.__name__)
print(coffee.__class__.__bases__[0].__name__)
print(coffee.name)
print(coffee.price)
print(coffee.milliliters)
print(coffee.caffeine)
tea = Tea("Swarz Tea", 3, 90)
print(tea.__class__.__name__)
print(tea.__class__.__bases__[0].__name__)
print(tea.name)
print(tea.price)
print(tea.milliliters)

